### ISSUE TITLE
[QUESTION] implementation of `get_p2p_cuda_stream_id` and `get_coll_cuda_stream_id`

### ISSUE THREAD

**Issue by nooblyh** [volcengine/veScale#46] opened 2024-08-12 06:12 UTC
In the README of ndtimeline, you mentioned implementing interfaces to obtain the streams for NCCL communication, specifically `get_p2p_cuda_stream_id` and `get_coll_cuda_stream_id`. However, these interfaces seem not present in the patches directory. Do you plan to release the specific implementation of these interfaces?

**Comment by vocaltract** [comment] 2024-08-13 17:00
Thanks a lot for your comments.  We will supplement these two functions soon.

**Comment by XLzed** [comment] 2024-08-18 06:22
> Thanks a lot for your comments. We will supplement these two functions soon.

Does the ndtimeline support async nccl stream like grad_reduce/params_gather overlap and interleaved p2p overlap? I add get_stream_id api in pytorch and use ndtimeline in megatron-lm trying to get the timeline of async nccl communication, but when I enable cudaEvent record I found the behavior of async nccl communication changed to sequential execution with computation kernel, is this normal? And how to fix it?

**Comment by XLzed** [comment] 2024-08-20 06:13
> > Thanks a lot for your comments. We will supplement these two functions soon.
> 
> Does the ndtimeline support async nccl stream like grad_reduce/params_gather overlap and interleaved p2p overlap? I add get_stream_id api in pytorch and use ndtimeline in megatron-lm trying to get the timeline of async nccl communication, but when I enable cudaEvent record I found the behavior of async nccl communication changed to sequential execution with computation kernel, is this normal? And how to fix it?

I found that the problem is caused by environment CUDA_DEVICE_MAX_CONNECTIONS=1, which is required by TP/SP communication overlap. But I don't know why it makes the async nccl op with ndtimer changed to sequential.

**Comment by vocaltract** [comment] 2024-08-26 03:48
Now [PR](https://github.com/volcengine/veScale/pull/48) is merged

**Closed by vocaltract** 2024-08-26 03:48 UTC
Labels: enhancement, question
